### ISSUE TITLE
How to get Grafana metrics into Prometheus

### ISSUE THREAD

**Issue by sedmaste** [MaibornWolff/dcos-thanos#3]
Hi, I'm trying to figure out how to get Grafana metrics into Prometheus.
Grafana has it's own metrics endpoint enabled.
For custom dcos services we deploy, it's just about to put following labels:
Example:
 ```
 {
        "containerPort": 9876,
        "labels": {
          "VIP_0": "/something/somethinelse/some_app:9876",
          "DCOS_METRICS_FORMAT": "prometheus",
          "DCOS_METRICS_ENDPOINT": "/metrics"
        }, 
```
Any ideas / hints how to get Thanos Grafana's metrics as target for Prometheus? 
Thank you for your support in advance.

**Comment by swoehrl-mw** [comment]
Hi @sedmaste, when grafana is deployed as part of the framework it is automatically added as a scrape target to prometheus (https://github.com/MaibornWolff/dcos-thanos/blob/master/files/prometheus.yml#L81) so grafana metrics should be available in prometheus without any extra configuration. If you cannot find the metrics please check the Prometheus UI if grafana appears in the scrape target list and is shown as healthy.

**Comment by sedmaste** [comment]
Hi @swoehrl-mw, thank you for your quick reply. I have verified Prometheus and metrics are there. So I guess this is resolved :) , thank you for help once again.
